Repository sipe-team/1-2_read_article, pull requests merged in 2023-12, with the labels that each got.

#31 [DOCS] week5 - 완료
  김상초/5주차/YouMightNotNeedAnEffect.md
  김상초/5주차/useEffect5tips.md
Labels: documentation, 5주차

#39 [DOCS] week6 - 완료
  김상초/6주차/reactHook.md
  김상초/6주차/rederPropsNhoc.md
Labels: 6주차

#35 docs: 5주차 정리
  조기문/5주차/README.md
Labels: 5주차
