Repository sipe-team/1-2_read_article, pull requests merged in 2023-11, with the labels that each got.

#2 [DOCS] Week1 완료
  README.md
  김상초/1주차/Get All That Network Activity Under Control with Priority Hints(번역).md
  김상초/1주차/디자인패턴-Compound.md
Labels: documentation

#25 [DOCS] week4 - 정리
  김상초/4주차/addEventListener.md
  김상초/4주차/stopPropgationAndStopImmiatePropgation.md
Labels: documentation

#30 [DOCS] week4 - add 01-kafka-schemaregistry-connect-kraft, 02-toss-For…
  김우재/2주차/01-jvm-warm-up.md
  김우재/2주차/02-circuit-breaker-pattern.md
  김우재/4주차/01-kafka-schemaregistry-connect-kraft.md
  김우재/4주차/02-toss-Foreign-ledger-transactions.md
Labels: 4주차

#24 [DOCS] week-4 정리
  강민주/week-4.md
Labels: 4주차

#26 [DOCS] 4주차 정리
  임지민/4주차/스프링과 문제 해결-예외처리, 반복.md
Labels: 4주차

#29 [DOCS] week-5 정리
  강민주/week-5.md
Labels: 5주차
